# Generated by Django 3.2.7 on 2021-10-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passener',
            new_name='Passenger',
        ),
    ]
